### ISSUE TITLE
Miss placed code inside Header file

### ISSUE THREAD

**Issue by alifarazz** [amirsojoodi/GPGPU-2018Fall#2]
Inside [12th/vectorOpGPU/vectorOp.h](https://github.com/amirsojoodi/GPGPU-2018Fall/blob/master/12th/vectorOpGPU/vectorOp.h), lines 8, 10 and 13 through 19 are programming logic related to [12th/vectorOpGPU/vectorOp.cu](https://github.com/amirsojoodi/GPGPU-2018Fall/blob/master/12th/vectorOpGPU/vectorOp.cu). They are useless outside their compilation unit.
Shouldn't the .cu(and .c) files contain all the code while the .h files contain declarations used in other .cu and .h files?

**Comment by amirsojoodi** [comment]
Thanks for your comment. First of all, it is under development! I am currently working on it.
And second, I removed those lines from the main file to gain more readability and help students to use the header files within their own projects effortlessly.
